### ISSUE TITLE
Sidebar + mask-strong makes vertical scroll 9999px

### ISSUE THREAD

**Issue by agavazov** [mdbootstrap/bootstrap-material-design#73]
Sidebar scroll is not working fine when ".sidenav-bg .mask-strong" are added.
Here is one of your examples with the bug https://mdbootstrap.com/live/_MDB/4.3.2/docs/page-layouts/side-nav-fixed-navbar-fixed.html

![bug1 fw](https://user-images.githubusercontent.com/1092357/28618127-f09d99f8-720b-11e7-981d-e679100b8611.png)

**Comment by agavazov** [comment]
Windows 10 with firefox 54.0.1 (32-bit)

**Comment by agavazov** [comment]
Another problem is when I want to use the native scroll (without the custom scroll bar)
There is no enough space for the mask.
Please remove min-with or extend the wrapper little bit

![bug1 fw](https://user-images.githubusercontent.com/1092357/28618350-c573ecfe-720c-11e7-9e8e-ddce4e3d78d6.png)

**Comment by agavazov** [comment]
btw in Chrome works fine (for both problems)

**Comment by Denis-Frolov** [comment]
Also in IE mask-strong bleeding all over the screen. 
Not trying to be authentic here, but as a temporary fix, I added this to the global css:
`.sidenav-bg {
    width:0 !important;    
    &:after {
        width: 0 !important;
        margin-bottom: 0 !important;
        padding-bottom: 0 !important;
    }
  }
`
It fixes all the issues above, accept horizontal scroll if firefox. That was caused by too wide search input field, which can be adjusted or removed.
